In [11]:
import pandas as pd
master = pd.DataFrame( { "TimeStamp": ['2020-01-01 01:01:02', '2020-01-01 01:01:04', '2020-01-01 01:01:06', '2020-01-01 01:01:08'], "a":[2,4,6,8] } )
master[ "TimeStamp" ] = pd.to_datetime(master[ "TimeStamp" ])

a = pd.DataFrame( { "TimeStamp": ['2020-01-01 01:01:01', '2020-01-01 01:01:02', '2020-01-01 01:01:03', '2020-01-01 01:01:04', '2020-01-01 01:01:05'], "Data":[11,12,13,14,15] } )
b = pd.DataFrame( { "TimeStamp": ['2020-01-01 01:01:06', '2020-01-01 01:01:07', '2020-01-01 01:01:08', '2020-01-01 01:01:09', '2020-01-01 01:01:10'], "Data":[16,17,18,19,20] } )
a[ "TimeStamp" ] = pd.to_datetime(a[ "TimeStamp" ])
b[ "TimeStamp" ] = pd.to_datetime(b[ "TimeStamp" ])

In [12]:
### WIN, but depends on order ###
pd.concat( [a,b] )

            TimeStamp  Data
0 2020-01-01 01:01:01    11
1 2020-01-01 01:01:02    12
2 2020-01-01 01:01:03    13
3 2020-01-01 01:01:04    14
4 2020-01-01 01:01:05    15
0 2020-01-01 01:01:06    16
1 2020-01-01 01:01:07    17
2 2020-01-01 01:01:08    18
3 2020-01-01 01:01:09    19
4 2020-01-01 01:01:10    20

In [13]:
### FAIL ###
pd.concat( [b,a] )

            TimeStamp  Data
0 2020-01-01 01:01:06    16
1 2020-01-01 01:01:07    17
2 2020-01-01 01:01:08    18
3 2020-01-01 01:01:09    19
4 2020-01-01 01:01:10    20
0 2020-01-01 01:01:01    11
1 2020-01-01 01:01:02    12
2 2020-01-01 01:01:03    13
3 2020-01-01 01:01:04    14
4 2020-01-01 01:01:05    15

In [14]:
### WIN ###
pd.merge_ordered( a,b )

            TimeStamp  Data
0 2020-01-01 01:01:01    11
1 2020-01-01 01:01:02    12
2 2020-01-01 01:01:03    13
3 2020-01-01 01:01:04    14
4 2020-01-01 01:01:05    15
5 2020-01-01 01:01:06    16
6 2020-01-01 01:01:07    17
7 2020-01-01 01:01:08    18
8 2020-01-01 01:01:09    19
9 2020-01-01 01:01:10    20

In [15]:
### WIN ###
pd.merge_ordered( b,a )

            TimeStamp  Data
0 2020-01-01 01:01:01    11
1 2020-01-01 01:01:02    12
2 2020-01-01 01:01:03    13
3 2020-01-01 01:01:04    14
4 2020-01-01 01:01:05    15
5 2020-01-01 01:01:06    16
6 2020-01-01 01:01:07    17
7 2020-01-01 01:01:08    18
8 2020-01-01 01:01:09    19
9 2020-01-01 01:01:10    20

In [16]:
### FAIL ###
pd.merge_ordered( a,b, on="TimeStamp")

            TimeStamp  Data_x  Data_y
0 2020-01-01 01:01:01    11.0     NaN
1 2020-01-01 01:01:02    12.0     NaN
2 2020-01-01 01:01:03    13.0     NaN
3 2020-01-01 01:01:04    14.0     NaN
4 2020-01-01 01:01:05    15.0     NaN
5 2020-01-01 01:01:06     NaN    16.0
6 2020-01-01 01:01:07     NaN    17.0
7 2020-01-01 01:01:08     NaN    18.0
8 2020-01-01 01:01:09     NaN    19.0
9 2020-01-01 01:01:10     NaN    20.0

In [17]:
### WIN, but not worth the extra effort? ###
pd.merge_ordered( a,b, on=["TimeStamp","Data"] )

            TimeStamp  Data
0 2020-01-01 01:01:01    11
1 2020-01-01 01:01:02    12
2 2020-01-01 01:01:03    13
3 2020-01-01 01:01:04    14
4 2020-01-01 01:01:05    15
5 2020-01-01 01:01:06    16
6 2020-01-01 01:01:07    17
7 2020-01-01 01:01:08    18
8 2020-01-01 01:01:09    19
9 2020-01-01 01:01:10    20

In [18]:
### NOT BAD YET ###
pd.merge_asof( master,a )

            TimeStamp  a  Data
0 2020-01-01 01:01:02  2    12
1 2020-01-01 01:01:04  4    14
2 2020-01-01 01:01:06  6    15
3 2020-01-01 01:01:08  8    15

In [19]:
### FAIL ###
pd.merge_asof( pd.merge_asof( master,a ), b )

MergeError: can only asof on a key for left

In [20]:
### FAIL ###
temp=pd.merge_asof( master,a )
pd.merge_asof( temp,b )

MergeError: can only asof on a key for left

In [21]:
### FAIL ###
pd.merge_asof( temp,b, on="TimeStamp" )

            TimeStamp  a  Data_x  Data_y
0 2020-01-01 01:01:02  2      12     NaN
1 2020-01-01 01:01:04  4      14     NaN
2 2020-01-01 01:01:06  6      15    16.0
3 2020-01-01 01:01:08  8      15    18.0

In [22]:
### FAIL, asof does not work like normal merge ###
pd.merge_asof( temp,b, on=["TimeStamp","Data"] )

MergeError: can only asof on a key for left

In [23]:
### WIN, and what needs to be in the final implementation ###
temp = pd.merge_ordered( a,b )
pd.merge_asof( master, temp )

            TimeStamp  a  Data
0 2020-01-01 01:01:02  2    12
1 2020-01-01 01:01:04  4    14
2 2020-01-01 01:01:06  6    16
3 2020-01-01 01:01:08  8    18

In [24]:
# Now let's explore missing data
# Defaulting to backwards:
# OK if data is front-aligned
pd.merge_asof( master,a )

            TimeStamp  a  Data
0 2020-01-01 01:01:02  2    12
1 2020-01-01 01:01:04  4    14
2 2020-01-01 01:01:06  6    15
3 2020-01-01 01:01:08  8    15

In [25]:
# But not great if data starts after clock:
pd.merge_asof( master, b )

            TimeStamp  a  Data
0 2020-01-01 01:01:02  2   NaN
1 2020-01-01 01:01:04  4   NaN
2 2020-01-01 01:01:06  6  16.0
3 2020-01-01 01:01:08  8  18.0

In [26]:
# Much Better
pd.merge_asof( master, b, direction='nearest')

            TimeStamp  a  Data
0 2020-01-01 01:01:02  2    16
1 2020-01-01 01:01:04  4    16
2 2020-01-01 01:01:06  6    16
3 2020-01-01 01:01:08  8    18

In [27]:
# Much Better
pd.merge_asof( master, a, direction='nearest')

            TimeStamp  a  Data
0 2020-01-01 01:01:02  2    12
1 2020-01-01 01:01:04  4    14
2 2020-01-01 01:01:06  6    15
3 2020-01-01 01:01:08  8    15

In [28]:
# Doesn't affect big picture (in this example at least)
temp = pd.merge_ordered( a,b )
pd.merge_asof( master, temp, direction='nearest' )

            TimeStamp  a  Data
0 2020-01-01 01:01:02  2    12
1 2020-01-01 01:01:04  4    14
2 2020-01-01 01:01:06  6    16
3 2020-01-01 01:01:08  8    18